;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; src_dir = examples/AllFunction
; src_dir = examples/ATDebug
; src_dir = examples/BIGIOT_Gnss_Upload
; src_dir = examples/BLE5_extended_scan
; src_dir = examples/BLE5_multi_advertising
; src_dir = examples/BLE5_periodic_advertising
; src_dir = examples/BLE5_periodic_sync
; src_dir = examples/MinimalCameraExample
; src_dir = examples/MinimalDeepSleepExample
;src_dir = examples/MinimalModemAndEspSleep
; src_dir = examples/MinimalLowBattPowerOffExample
; src_dir = examples/MinimalModemGPSExample
; src_dir = examples/MinimalModemNBIOTExample
; src_dir = examples/MinimalModemPowerSaveMode
; src_dir = examples/MinimalModemSleepMode
; src_dir = examples/MinimalModemUpgrade
; src_dir = examples/MinimalPowersCurrentExample
; src_dir = examples/MinimalPowersExample
; src_dir = examples/MinimalSDCardExample
; src_dir = examples/ModemFileUploadExample
; src_dir = examples/ModemMqttPublishExample
; src_dir = examples/ModemMqttsAuthExample
; src_dir = examples/ModemMqttsExample
; src_dir = examples/ModemMqttSubscribeExample

; By @bootcampiot https://github.com/bootcampiot
; src_dir = examples/SIM7080G-ATT-NB-IOT-AWS-MQTT
; src_dir = examples/SIM7080G-ATT-NB-IOT-HTTP-HTTPS
; src_dir = examples/SIM7080G-ATT-NB-IOT-SSL-Mosquitto

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32s3box
upload_speed =  921600
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM       
    ; Enable DARDUINO_USB_CDC_ON_BOOT will start printing and wait for terminal access during startup
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; Enable UARDUINO_USB_CDC_ON_BOOT will turn off printing and will not block when using the battery
    ; -UARDUINO_USB_CDC_ON_BOOT
    -DTINY_GSM_MODEM_SIM7080
    -DTINY_GSM_YIELD_MS=10
    -DTINY_GSM_RX_BUFFER=1024
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUHAL_LOG_COLORS
    ;-DDUMP_AT_COMMANDS
    ; -D PIO_CI     -D WIFI_PASS=\"TEST\" -D WIFI_SSID=\"TEST\"  -D MQTT_SERVER=\"TEST\"  -D MQTT_TOPIC=\"TEST\"  -D CMD_TOPIC=\"TEST\"  -D MQTT_USER=\"TEST\"  -D MQTT_PASS=\"TEST\"  -D MQTT_PORT=8000
board_build.partitions = default_16MB.csv
board_build.f_cpu = 240000000
board_build.f_flash = 80000000
board_build.flash_mode = qio
; board_build.embed_txtfiles = 
;     src\ssl\mqtt_client.crt
;     src\ssl\mqtt_client.key
board_build.filesystem = littlefs

lib_deps = 
	fastled/FastLED@^3.6.7
	ElectronicCats/mpu6050
    PubSubClient
monitor_filters = esp32_exception_decoder

[env:usb]
upload_protocol = esptool
upload_speed = 115200

[env:ota]
upload_protocol = espota
upload_port = 192.168.1.23
