name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        env:
          PLATFORMIO_BUILD_FLAGS: -D PIO_CI
                                  -D WIFI_PASS=\"${{secrets.WIFI_PASS}}\"
                                  -D WIFI_SSID=\"${{secrets.SSID}}\"
                                  -D MQTT_SERVER=\"${{secrets.MQTT_SERVER}}\"
                                  -D MQTT_TOPIC=\"${{secrets.MQTT_TOPIC}}\" 
                                  -D CMD_TOPIC=\"${{secrets.CMD_TOPIC}}\"
                                  -D MQTT_USER=\"${{secrets.MQTT_USER}}\"
                                  -D MQTT_PASS=\"${{secrets.MQTT_PASS}}\"
                                  -D MQTT_PORT=${{secrets.MQTT_PORT}}
        run: pio run -e usb

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Rename firmware with timestamp
        run: |
          mkdir -p artifacts
          cp .pio/build/usb/firmware.elf artifacts/firmware_${{ steps.timestamp.outputs.timestamp }}.bin

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware_${{ steps.timestamp.outputs.timestamp }}
          path: artifacts/firmware_${{ steps.timestamp.outputs.timestamp }}.bin
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/firmware_${{ steps.timestamp.outputs.timestamp }}.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
